Implement sort list for applicant
AY2122S2-CS2103-W17-4/tp pull request #158
Opened 2022-03-28 23:55 UTC by khoahre123

The list command now accepts optional arguments `SORT_ARGUMENT` beside the `filter` function. The syntax for sort command is list -X s/FILTER_ARGUMENT.

2022-03-29 01:25 UTC, khoahre123 commented
Able to sort the list into position, but can not display into UI. Need to change UI

2022-03-30 15:06 UTC, goalfix requested changes
Some issues with code quality raised.  Good effort regardless!

2022-03-30 15:06 UTC, goalfix commented on src/main/java/seedu/address/model/interview/Interview.java
> +        requireAllNonNull(applicant, date, status);
Position should not be null too

2022-03-30 16:26 UTC, goalfix approved these changes
LGTM!

2022-03-30 16:26 UTC, merged